### ISSUE TITLE
Process not found

### ISSUE THREAD

**Issue by DougRogers** [avipreshel/NativeMemoryLeakDetection#1]
I compiled my app (Tinta.exe).  All the .dlls and .pdb files are in the directory.
```
C:\Users\Roger\source\repos\Projects\Master\Tinta\Debug>NativeHeapLeakageFinder tinta.exe -top:10 -hidesystemstack -ignoresingleallocs

Unhandled Exception: System.Exception: Process tinta not found
   at NativeHeapLeakageFinder.Program.GetProcessHandles(String processName) in C:\Users\Roger\source\repos\Projects\ExternalProjects\NativeMemoryLeakDetection\NativeHeapLeakageFinderApp\Program.cs:line 119
   at NativeHeapLeakageFinder.Program.Main(String[] args) in C:\Users\Roger\source\repos\Projects\ExternalProjects\NativeMemoryLeakDetection\NativeHeapLeakageFinderApp\Program.cs:line 26
```

**Comment by avipreshel** [comment]
I haven't checked the code, but maybe it's case sensitive? you wrote the process name with capital letter ("Tinta") yet you passed it to the CLI with lowercase.

**Comment by DougRogers** [comment]
I did not realize you had to start the executable and attach to the process.
